<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class CheckInventoryPartsCsv extends Command
{
    use CommandHelpers, CsvHelpers, CheckHelpers;

    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'lego:check-inventory-parts-csv
                            {--bulk : Command being run with other commands}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Verifies that all table dependencies are present from csv file generated by Rebrickable.';

    /**
     * CSV File Url
     *
     * @var string
     */
    protected $url = 'https://cdn.rebrickable.com/media/downloads/inventory_parts.csv.gz';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();

        $this->checkTables = [
            'inventories' => ['id', 'inventory_id'],
            'parts' => ['part_num', 'part_num'],
            'colors' => ['id', 'color_id']
        ];

        $this->missingDeps = $this->loadedDeps = [
            'inventories' => [],
            'parts' => [],
            'colors' => []
        ];

        $this->keys = collect([
            'inventory_id',
            'part_num',
            'color_id',
            'quantity',
            'is_spare',
        ]);
    }

    /**
     * Display command details and request confirmation to continue
     *
     * @return bool
     */
    protected function start()
    {
        $this->info('>> Please wait while we verify all the dependencies are available for Inventory Parts <<');
        return true;
    }
}
