<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class CheckInventoriesCsv extends Command
{
    use CommandHelpers, CsvHelpers, CheckHelpers;

    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'lego:check-inventories-csv
                            {--bulk : Command being run with other commands}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Verifies that all table dependencies are present from csv file generated by Rebrickable.';

    /**
     * CSV File Url
     *
     * @var string
     */
    protected $url = 'https://cdn.rebrickable.com/media/downloads/inventories.csv.gz';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();

        $this->checkTables = [
            'sets' => ['set_num', 'set_num']
        ];

        $this->missingDeps = $this->loadedDeps = [
            'sets' => []
        ];

        $this->keys = collect([
            'id',
            'version',
            'set_num',
        ]);
    }

    /**
     * Display command details and request confirmation to continue
     *
     * @return bool
     */
    protected function start()
    {
        $this->info('>> Please wait while we verify all the dependencies are available for Inventories <<');
        return true;
    }
}
